### ISSUE TITLE
Ensure release version on README is not incorrect

### ISSUE THREAD

**Issue by scottrigby** [open-gitops/documents#25]
## Good fix for #20

On the `main` branch we now use a `{{version}}` placeholder at the top of PRINCIPLES.md markdown file, as a way to solve https://github.com/open-gitops/documents/issues/20.

## Incomplete though

However, we forgot to resolve this in the README 🤦, which still links to the first pre-release:

>The current version [v0.1.0](https://github.com/open-gitops/documents/releases/tag/v0.1.0) is a pre-release, which includes:
>
>- [GitOps Principles](https://github.com/open-gitops/documents/blob/v0.1.0/PRINCIPLES.md)
>- [GitOps Glossary](https://github.com/open-gitops/documents/blob/v0.1.0/PRINCIPLES.md#glossary)

Sigh.

## Proposed solutions

1. change the README to use a placeholder
    - pros: the `{{version}}` => semver replacement could be automated, just as we plan to do for the PRINCIPLES.md on release branches
    - cons: users who encounter the readme would likely be confused by broken links on `main`
2. change the text above to just point to the list of releases and milestones for planned upcoming releases
    - pros: the README will be clear to new users. also don't have to update it for every new release
    - cons: README won't list the current version on `main`
3. solve README differently than PRINCIPLES.md, since the goal is different. On PRINCIPLES.md we don't want the previously published version to be displayed after new commits are added to `main`, because of #20. However in the README we (may) want to list the most recently published version. Perhaps this could be solved by a GitHub action.

How about we start with option 2, and consider option 3 when we get around to making a release workflow using gh actions (similar to https://github.com/helm/chart-testing#releasing).

**Comment by lloydchang** [comment]
2️⃣

**Comment by lloydchang** [comment]
2
