### ISSUE TITLE
German translation of GitOps principles

### ISSUE THREAD

**Issue by schlomo** [open-gitops/documents#52]
I need a German translation of the principles and I will be happy to coordinate the work on that.

Anybody interested please contribute to https://docs.google.com/document/d/1uwcNXo-hfJsqloW58pjByE3nVI-0zNHGeg47E9aAvAc/edit?usp=sharing

**Comment by scottrigby** [comment]
@heubeck agreed (also per discussion in https://github.com/open-gitops/project/issues/28)

**Comment by mschwrdtnr** [comment]
@scottrigby think this issue was solved by #58 :)

**Comment by christianh814** [comment]
Closed by #58
