### ISSUE TITLE
Operational Concerns

### ISSUE THREAD

**Issue by tpouyer** [open-gitops/documents#54]
So far I've mostly seen GitOps described from a "developers" persona.  Several of the "GitOps benefits" described in the [README](https://github.com/fluxcd/gitops-working-group#the-what-and-why-of-gitops) list benefits that are more "operational" in nature:

- Increased Developer & __Operational Productivity__
- __Improved Stability__
- __Higher Reliability__

Given these "operational" benefits I believe it would be good to include "operator" persona in this GitOps Manifesto.  Some "operational" concerns that come to my mind would be:

- User/Identity Management between "git" and "k8s" i.e. should the set of users be shared between them or should they be purposefully different
- Secret Management (which has already been mentioned separately in Issue gitops-working-group/gitops-working-group-old#16)
- Git Repo Sprawl i.e. how does an "operator" reconstruct all the applications/deployments/configuration for a specific k8s cluster from all the possible git repos that "control" the intended state of the cluster in the case of Disaster Recovery

I'm sure there are other concerns "operators" will have with GitOps that should be addressed by this GitOps Manifesto.

**Comment by scottrigby** [comment]
Hi @tpouyer just moved this issue to the OpenGitOps documents repo. Check out the v1.0 of the GitOps Principles and Glossary! The WG is now focusing on developing best practices and other things. Please join these fortnightly meetings, and also say hi to us on Slack! Here is a good list of ways to get involved: https://opengitops.dev/get-involved

**Comment by christianh814** [comment]
@scottrigby Okay to close? I think the release of the principals address this issue. If there are more specific issues (with respect to best practices and blueprints), I think that's another issue/PR.

**Comment by scottrigby** [comment]
@christianh814 I agree. The [Software System](https://github.com/open-gitops/documents/blob/v1.0.0/GLOSSARY.md#software-system) glossary item linked from the first principle addresses this. I just wanted to give folks who added early issues a chance to get involved now that we have a foundation 🙂
