### ISSUE TITLE
Principles are no longer numbered on main

### ISSUE THREAD

**Issue by scottrigby** [open-gitops/documents#68]
Adding anchor links to each principle was a good idea, per https://github.com/open-gitops/project/discussions/166.

Thanks for implementing that in this PR. However, the PR also changed the markdown ordered list to an unordered list, which – according to our recorded principle committee meetings and Kubecon talks where we explain on stage that the order matters, as each principle must build upon the previous ones – we want to keep the numbers. https://github.com/open-gitops/documents/pull/67

Please re-add principle numbering. Thanks!

**Comment by samueltauil** [comment]
Should all the translations be packed in the same PR to add anchor and numbering as well?

**Comment by christianh814** [comment]
> Should all the translations be packed in the same PR to add anchor and numbering as well?

Yes, I think so!
