### ISSUE TITLE
Minor addition to Language README.md

### ISSUE THREAD

**Issue by Kristianwhittick** [open-gitops/documents#75]
In the Language README.md I suggest name language also both in English in their own language.

https://github.com/open-gitops/documents/blob/main/i18n/README.md

Change to this:

**German / Deutsch
Spanish / Español
Portuguese / Português
French / Français**

OR Change to this:

**Deutsch (German)
Español (Spanish)
Português (Portuguese)
Français (French)**

**Comment by scottrigby** [comment]
@Kristianwhittick would you like to open a PR for this?

**Comment by nishadmehendale** [comment]
#92 created.

**Comment by nishadmehendale** [comment]
@todaywasawesome we should be able to close this.
